core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("developers/", include("resumes.urls")),
    path("", include("pages.urls")),
    path("admin/", admin.site.urls),
]

pages/urls.py
from .views import about, home
from django.urls import path

app_name = "pages"

urlpatterns = [
    path("about", about, name="about"),
    path("", home, name="root"),
]

resumes/urls.py
from . import views
from django.urls import path

app_name = "resume"  # 因不同app中可能有index、show所以需要作出一個空間


urlpatterns = [
    path("", views.index, name="index"),
    path("new", views.new, name="new"),
    path("<int:id>", views.show, name="show"),
    path("<int:id>/edit", views.edit, name="edit"),
    path("<int:id>/delete", views.delete, name="delete"),
]

resumes/models.py
from django.db import models


# Create your models here.
class Resume(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    introduce = models.CharField(max_length=200)
    profile = models.TextField()
    online = models.BooleanField(default=False)

    # 後臺資料庫可以印出名字(客製化)
    def __str__(self):
        return f"{self.name} {(self.email)}"

resumes/forms/resume_form.py
from django.forms import ModelForm
from resumes.models import Resume
from django.forms.widgets import TextInput, Textarea, CheckboxInput, EmailInput


# 建立表單
class ResumeForm(ModelForm):
    class Meta:
        model = Resume
        fields = [
            "name",
            "email",
            "introduce",
            "profile",
            "online",
        ]  # 只開放這些丟過來，其他都會被濾掉

        widgets = {
            "name": TextInput(attrs={"class": "input"}),
            "email": EmailInput(attrs={"class": "input"}),
            "introduce": TextInput(attrs={"class": "input"}),
            "profile": Textarea(attrs={"rows": "5", "class": "textarea"}),
            "online": CheckboxInput(attrs={"class": "input"}),
        }
        labels = {
            "name": "姓名",
            "email": "Email",
            "introduce": "簡介",
            "profile": "個人檔案",
            "online": "是否上線",
        }

pages/views.py
from django.shortcuts import render


def about(req):
    return render(req, "pages/about.html")


def home(req):
    return render(req, "pages/home.html")

resumes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import Resume
from django.http import HttpResponse
from .forms import ResumeForm
from django.urls import reverse

# Create your views here.


def index(req):
    if req.method == "POST":
        # form元件(去forms找)
        form = ResumeForm(req.POST)
        if form.is_valid():
            form.save()  # 叫表單存檔
            messages.success(req, "新增成功")
            return redirect(reverse("resume:index"))  # reverse 把字串換成url_for
        else:
            messages.error(req, "新增失敗")
            return render(req, "resumes/new.html", {"form": form})

    resumes = Resume.objects.all()  # 拿取所有資料
    return render(
        req,
        "resumes/index.html",
        {"resumes": resumes},
    )  # 將資料傳到index.html


def new(req):
    form = ResumeForm()
    return render(req, "resumes/new.html", {"form": form})


def show(req, id):
    resume = get_object_or_404(Resume, pk=id)
    if req.method == "POST":
        # form元件(去forms找)
        form = ResumeForm(req.POST, instance=resume)
        if form.is_valid():
            form.save()  # 叫表單存檔
            messages.success(req, "更新成功")
            return redirect("resume:show", resume.id)  # reverse 把字串換成url_for
        else:
            messages.error(req, "更新失敗")
            return render(req, "resumes/edit.html", {"form": form, "resume": resume})
    resume = get_object_or_404(Resume, pk=id)
    return render(req, "resumes/show.html", {"resume": resume})


def edit(req, id):
    resume = get_object_or_404(Resume, pk=id)
    form = ResumeForm(instance=resume)  # 把resume餵給ResumeForm
    return render(req, "resumes/edit.html", {"form": form, "resume": resume})


def delete(req, id):
    resume = get_object_or_404(Resume, pk=id)
    resume.delete()
    messages.success(req, "刪除成功")
    return redirect("resume:index")

pages/templates/pages/about.html
{%extends 'layouts/base.html'%}
{%block content%}
<h1>關於我們</h1>
{%endblock%}

pages/templates/pages/home.html
{%extends 'layouts/base.html'%}
{%load static%}
{%block content%}
<h1>首頁</h1>
<img src="{% static 'images/cute.png' %}">
{%endblock%}

resumes/templates/resumes/edit.html
{%extends 'layouts/base.html'%}

{%block content%}
<h1>新增 Resume</h1>
<form action="{%url 'resume:show' resume.id%}" method="Post">
    {%csrf_token%}
    {%for field in form%}
    <div class="form-control">
        <label class="label">{{field.label}}</label>
        {{field}}
        <span class="text-red-500">{{field.errors}}</span>
    {%endfor%}
    
    <div>
        <button class="btn btn-primary">更新</button>
    </div>
{%endblock%}

resumes/templates/resumes/index.html
{%extends 'layouts/base.html'%}

{%block content%}
<h1>Developers</h1>
<a href="{%url 'resume:new'%}" class="btn btn-primary">新增</a>

<ul>
    {% for resume in resumes%}
    <li>
        {{resume.name}}
        <a href="{% url 'resume:show' resume.id%}">{{resume.email}}</a>
        <a href="{% url 'resume:edit' resume.id%}" class=" btn-primary">更新</a>
        <a href="{% url 'resume:delete' resume.id%}" class=" btn-primary">刪除</a>
    </li>
    {%endfor%}
</ul>
{%endblock%}

resumes/templates/resumes/new.html
{%extends 'layouts/base.html'%}

{%block content%}
<h1>新增 Resume</h1>
<form action="{%url 'resume:index'%}" method="Post">
    {%csrf_token%}
    {%for field in form%}
    <div class="form-control">
        <label class="label">{{field.label}}</label>
        {{field}}
        <span class="text-red-500">{{field.errors}}</span>
    {%endfor%}
    
    <div>
        <button class="btn btn-primary">新增</button>
    </div>
{%endblock%}

resumes/templates/resumes/show.html
{%extends 'layouts/base.html'%}

{%block content%}
<h1>{{resume.name}}</h1>
<h2>{{resume.email}}</h2>
{%endblock%}

templates/layouts/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
        <link rel="stylesheet" href="{%static 'styles/style.css'%}">
    </head>
    <body>
        {%include 'shared/navbar.html'%}
        {%include 'shared/flash.html'%}
        <main class="container mx-auto my-2">
        
       
        {% block content %}
        {%endblock%}
        </main>

    </body>
</html>

templates/shared/flash.html
{%if messages%}
<div x-data x-ref="flash" class="flash ">
<ul class="w-full">
    {%for message in messages %}
    <li class="{{message.tags}}">
        {{message}}
    </li>
    {%endfor%}
</ul>
<button class="w-6 h-6 " @click="$refs.flash.remove()">X</button>
</div>
{%endif%}

templates/shared/navbar.html
<nav class="bg-[#F2D57E] flex justify-between px-6 py-2">
    <ul class="flex gap-4">
      <li><a href="{% url 'pages:root' %}">首頁</a></li>
      <li><a href="{% url 'pages:about'%}">關於我們</a></li>
      <li><a href="{% url 'resume:index'%}">Developers</a></li>
    </ul>
    <ul class="flex gap-4">
      <li>註冊</li>
      <li>登入</li>
    </ul>
  </nav>